apiVersion: v1
kind: Pod
metadata:
  name: origin
  namespace: hubs
spec:
  containers:
  - name: nginx
    image: nginx
  - name: redis
    image: redis
  - name: memcached
    image: memcached







